[browser]
gatherUsageStats = false


[theme]
primaryColor = "#ffffff"  # White background
backgroundColor = "#ffffff"  # White background
textColor = "#333333"  # Dark gray text
font = "sans serif"


[ui]
hide_top_bar = true